### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [Itsuki-M/FF14_MatchingApp#79]
LGTMです
下記にレビュー内容を記載します
本リリースに向けて実装を進めていきましょう！

## マッチングに関して
roleをタンクとヒーラーにして同じ内容でマッチング募集を行ったのですがマッチしませんでした。
バグかどうか確認をお願いします(後から内容変更したりしたらマッチしないとかありますかね？)

マッチング募集を出した際に実際にマッチングが出来るのかどうか、どのくらいの人が、どういう条件でマッチング待ちをしているのかがわからず不安になるので、マッチング待ちリストのような物を表示すると良いかなと思いました。

FF14の母数や詳細がわからないのでなんともって感じなのですが条件が全く同じだとマッチングが出来るという感じになっているので複数の条件を選べるようになったりすると(バハムートってやつと他のなにかみたいな感じ)よりマッチングしやすくなるかなと思いました。
この辺は実際に使ってもらってユーザーの声を聞けると良いかなと思います

上記に加えて本リリースまでに実装予定のマッチング通知機能があるとより使いやすそうです

## コードの細かいところ
また、細かいですがpartysではなくpartiesの方が良いのかなと思ったりしてます
https://ja.wiktionary.org/wiki/parties#:~:text=parties

**Comment by Itsuki-M** [comment]
レビューありがとうございます！

> roleをタンクとヒーラーにして同じ内容でマッチング募集を行ったのですがマッチしませんでした。

これについてはちょっと調べてみます。
一応タンク2 ヒーラー2 DPS4の構成じゃないとマッチしないようになっているので、タンクとヒーラーのみになってたらマッチしないかもしれません。

> マッチング募集を出した際に実際にマッチングが出来るのかどうか、どのくらいの人が、どういう条件でマッチング待ちをしているのかがわからず不安になるので、マッチング待ちリストのような物を表示すると良いかなと思いました。

確かにそういう表みたいなものがあると、視覚的にわかりやすくて、先輩プレイヤーの人が手助けでマッチング入れる際とかも参考にしやすいので、実装させていただきます。

> FF14の母数や詳細がわからないのでなんともって感じなのですが条件が全く同じだとマッチングが出来るという感じになっているので複数の条件を選べるようになったりすると(バハムートってやつと他のなにかみたいな感じ)よりマッチングしやすくなるかなと思いました。

確かに複数で出した方が、マッチング時間も短縮されてより集まりやすくなる気がします。
これも実装させていただきます。

> partysではなくpartiesの方が良いのかなと思ったりしてます

早急に直します。

これらはissueにタスクとして落とし込んで、本リリースに向けて実装していくという形で大丈夫ですよね？

**Comment by kenchasonakai** [comment]
> これらはissueにタスクとして落とし込んで、本リリースに向けて実装していくという形で大丈夫ですよね？

それで大丈夫です🙆
どんどん進めちゃってください
